package damjay.control.ghosthand;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import damjay.control.ghosthand.net.GhostProtocol;

/**
 * Entry point: pick a role.
 *
 * <p>GhostHand is one APK that runs on both phones. Which half of the code wakes up
 * is decided here - {@link HostActivity} (capture + serve) or {@link GuestActivity}
 * (discover + decode + display). Keeping both roles in one app means you install the
 * same build on two phones and never wonder which one has which flavour.
 *
 * <p><b>What AndroidX changed here.</b> The activity now extends
 * {@link AppCompatActivity}, so it gets the AppCompat widget factory: every view in
 * the layout is inflated by AppCompat's {@code AppCompatViewInflater}, which means
 * the Material 3 theme actually reaches the widgets. The views are still found with
 * {@code findViewById} - view binding is generated by the Android Gradle Plugin,
 * which this repo deliberately does not use, so the ids in the layout stay the
 * contract between XML and Java.
 */
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);   // AppCompat's interop shim: toolbar -> ActionBar

        TextView footer = findViewById(R.id.txtFooter);
        footer.setText(getString(R.string.main_footer,
                GhostProtocol.DEFAULT_PORT, GhostProtocol.HEADER_SIZE));

        View hostCard = findViewById(R.id.cardHost);
        hostCard.setOnClickListener(v ->
                startActivity(new Intent(this, HostActivity.class)));

        View guestCard = findViewById(R.id.cardGuest);
        guestCard.setOnClickListener(v ->
                startActivity(new Intent(this, GuestActivity.class)));
    }
}
